




.build/uno/src/Calibration.cpp : src/Calibration.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/Calibration.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/Calibration.cpp
	@true

